version: "3.8"


services:
  nginx:
    restart: "no"

  redis:
    restart: "no"

  postgres:
    env_file: .env.development
    restart: "no"

  rq:
    environment:
      - FLASK_ENV=development
      - CONFIG_NAME=development
    env_file: .env.development
    restart: "no"

  app:
    volumes:
      - ./src:/home/yd-tg-bot/app/src
      - ./migrations:/home/yd-tg-bot/app/migrations
    environment:
      - FLASK_ENV=development
      - CONFIG_NAME=development
    env_file: .env.development
    restart: "no"
