from .unknown import handle as unknown_handler
from .help import handle as help_handler
from .about import handle as about_handler
from .settings import handle as settings_handler
from .yd_auth import handle as yd_auth_handler
from .yd_revoke import handle as yd_revoke_handler
from .upload import photo_handler as upload_photo_handler
from .upload import file_handler as upload_file_handler
from .upload import audio_handler as upload_audio_handler
from .upload import video_handler as upload_video_handler
from .upload import voice_handler as upload_voice_handler
from .create_folder import handle as create_folder_handler
