"""Init

Revision ID: 1665a31ad4d5
Revises: 
Create Date: 2020-03-28 20:30:04.190376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1665a31ad4d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False, comment='Unique ID to identificate user in Telegram'),
    sa.Column('is_bot', sa.Boolean(), nullable=False, comment='User is bot in Telegram'),
    sa.Column('language', sa.Enum('EN', name='supportedlanguages'), nullable=False, comment='Preferred language of user'),
    sa.Column('group', sa.Enum('USER', 'TESTER', 'ADMIN', name='usergroup'), nullable=False, comment='User rights group'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
