"""Add new user setting: public upload by default

Revision ID: 2806d4dc492a
Revises: 9181b112085e
Create Date: 2021-06-19 12:46:09.947331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2806d4dc492a'
down_revision = '9181b112085e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_upload_by_default', sa.Boolean(), nullable=True, comment='Until user explicitly specifies, public uploading may be used automatically'))

    op.execute(
        'UPDATE user_settings SET public_upload_by_default = false'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('public_upload_by_default')

    # ### end Alembic commands ###
