"""Change token lifetime type from int to bigint

Revision ID: 88ea91f132b7
Revises: a8a543539e0a
Create Date: 2020-03-30 18:31:52.507968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ea91f132b7'
down_revision = 'a8a543539e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yandex_disk_tokens', schema=None) as batch_op:
        batch_op.alter_column('access_token_expires_in',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('insert_token_expires_in',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yandex_disk_tokens', schema=None) as batch_op:
        batch_op.alter_column('insert_token_expires_in',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('access_token_expires_in',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
