"""Change token expiration type from datetime to integer

Revision ID: a8a543539e0a
Revises: 7b80d376d639
Create Date: 2020-03-30 17:01:12.888231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a543539e0a'
down_revision = '7b80d376d639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yandex_disk_tokens', schema=None) as batch_op:
        batch_op.alter_column('access_token_expires_in',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('insert_token_expires_in',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yandex_disk_tokens', schema=None) as batch_op:
        batch_op.alter_column('insert_token_expires_in',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('access_token_expires_in',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
