"""Add index property for frequent columns

Revision ID: c8db92e01cf4
Revises: 67ffbddd6efe
Create Date: 2020-11-24 22:27:44.498208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8db92e01cf4'
down_revision = '67ffbddd6efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chats_telegram_id'), ['telegram_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    with op.batch_alter_table('yandex_disk_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yandex_disk_tokens_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yandex_disk_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yandex_disk_tokens_user_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chats_telegram_id'))

    # ### end Alembic commands ###
