"""Add chat model

Revision ID: e132de254282
Revises: c6fa89936c27
Create Date: 2020-03-29 13:09:07.810378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e132de254282'
down_revision = 'c6fa89936c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Unique ID to identificate chat in Telegram'),
    sa.Column('type', sa.Enum('PRIVATE', 'GROUP', 'SUPERGROUP', 'CHANNEL', name='chattype'), nullable=False, comment='Type of Telegram chat'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Through this chat message can be sent to this user'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chats')
    # ### end Alembic commands ###
